---
broker_url: "https://broker.io.nrs.gov.bc.ca"
action_token: "{{ lookup('ansible.builtin.env', 'ACTION_TOKEN_INSTALL') }}"
_jdk_type: ""
_jdk_major_version: ""
_jdk_url: ""
_jdk_release_name: ""
_log_dir: ""
_log_filename: ""
_log_level: ""
_log_type: ""
_tomcat_version: ""
_tomcat_port: ""
